### PR TITLE
Complete 1.21.11 port

### LINKED ISSUE #6: 1.21.11 update
~~The mod now crashes and needs an update for the newest Minecraft version 1.21.11
again, thank you for you time and dedication ❤
logs:
https://mclo.gs/7oVCItC~~

Edit: I ported it myself https://github.com/ItsJustMiaouss/ijm-tweaks/pull/7

### PR DESCRIPTION
**Pull request by adr278**
* 1.21.11 port.
* Loom updated to 1.14.7.
* Gradle updated to 9.2.1.
* modmuss50 Mod publish plugin updated to 1.1.0.
* Added/Updated Workflows.
* Migrated and Remapped to Mojang Mappings.

--> Opened a new new PR as I've cleaned up a lot of unnecessary changes, made a 1.21.11 port and Mojmappings migration since Yarn is ded. (and because I realized Fabrishot wasn't a dependency lol)

Release avaliable on my [repository](https://github.com/adr278/ijm-tweaks/releases/tag/v1.6.0%2B1.21.11)

### CODE REVIEW

File: src/main/java/com/itsjustmiaouss/ijmtweaks/mixin/EntityHitboxDebugRendererMixin.java
Comment (ItsJustMiaouss) [inline src/main/java/com/itsjustmiaouss/ijmtweaks/mixin/EntityHitboxDebugRendererMixin.java:1]: The internal code has changed and now entity models are shown instead of just rendering their hitboxes. Can you take a look at ``EntityHitboxDebugRenderer#emitGizmos``?

File: src/main/java/com/itsjustmiaouss/ijmtweaks/permission/Permission.java [hunk 1]
```diff
@@ -1,32 +1,32 @@
...
+        if (instance.isLocalServer()) return true;
 
-        ClientPlayerEntity player = instance.player;
+        LocalPlayer player = instance.player;
         if (player == null) return false;
 
         return switch (requirement) {
             case NON_SURVIVAL -> !isSurvivalLike();
-            case NON_SURVIVAL_OP -> !isSurvivalLike() && player.hasPermissionLevel(4);
+            case NON_SURVIVAL_OP -> !isSurvivalLike() && player.getAbilities().instabuild;
```
Comment (ItsJustMiaouss) [inline src/main/java/com/itsjustmiaouss/ijmtweaks/permission/Permission.java]: I don't really know what ``instabuild`` is. Maybe you can try something like this instead?
```suggestion
case NON_SURVIVAL_OP -> !isSurvivalLike() && player.permissions().hasPermission(Permissions.COMMANDS_ADMIN);
```

File: src/main/java/com/itsjustmiaouss/ijmtweaks/keybind/IJMTweaksBindings.java [hunk 2]
```diff
@@ -20,7 +20,7 @@ public static void registerBindings() {
         zoomKeyBinding = KeyBindingHelper.registerKeyBinding(new KeyMapping(
                 "key.ijmtweaks.zoom",
                 InputConstants.Type.KEYSYM,
-                GLFW.GLFW_KEY_R,
+                GLFW.GLFW_KEY_Y,
```
Comment (ItsJustMiaouss) [inline src/main/java/com/itsjustmiaouss/ijmtweaks/keybind/IJMTweaksBindings.java]: Good catch! I usually unbind the "reload shaders" from Iris. But what about the ``C`` key instead, it seems easier to reach? :)

**Review by ItsJustMiaouss — CHANGES_REQUESTED** [review]
Thank you very much for updating the mod! :) You did really great!

**Comment by adr278** [comment]
> Thank you very much for updating for mod! :) You did really great!

thank you, I did my best, I basically just began my coding journey

File: src/main/java/com/itsjustmiaouss/ijmtweaks/keybind/IJMTweaksBindings.java (hunk 2 above)
Comment (adr278) [reply src/main/java/com/itsjustmiaouss/ijmtweaks/keybind/IJMTweaksBindings.java]: will do 👍

File: src/main/java/com/itsjustmiaouss/ijmtweaks/mixin/EntityHitboxDebugRendererMixin.java
Comment (adr278) [reply src/main/java/com/itsjustmiaouss/ijmtweaks/mixin/EntityHitboxDebugRendererMixin.java:1]: > The internal code has changed and now entity models are shown instead of just rendering their hitboxes. Can you take a look at `EntityHitboxDebugRenderer#emitGizmos`?

I can give it a try yes 👍

Comment (adr278) [reply src/main/java/com/itsjustmiaouss/ijmtweaks/mixin/EntityHitboxDebugRendererMixin.java:1]: > The internal code has changed and now entity models are shown instead of just rendering their hitboxes. Can you take a look at `EntityHitboxDebugRenderer#emitGizmos`?

was it rendering block entity hitboxes and I didn't notice it or something like that?

Comment (adr278) [reply src/main/java/com/itsjustmiaouss/ijmtweaks/mixin/EntityHitboxDebugRendererMixin.java:1]: > The internal code has changed and now entity models are shown instead of just rendering their hitboxes. Can you take a look at `EntityHitboxDebugRenderer#emitGizmos`?

can I reach you outside of git? something like discord would be amazing, I'm a mod in a discord server where we discuss [BBE](https://modrinth.com/mod/better-block-entities) and you're welcome to [join us](https://discord.gg/NdX9BYpTtz) :). I'm currently helping the dev since it's a huge mod, and talking and trying to figure stuff out here is kinda hard lol. feel free to add me: my dc id 268108477958848532. I will commit the changes you requested but I literally have no idea if that is what you wanted me to do since the end result seems to be the exact same, so please if you can reach me through discord 🙏 that would be a lot better and faster lol. it is totally fine if you don't want to though, no problem with that 👍

Comment (ItsJustMiaouss) [reply src/main/java/com/itsjustmiaouss/ijmtweaks/mixin/EntityHitboxDebugRendererMixin.java:1]: > was it rendering block entity hitboxes and I didn't notice it or something like that?

The expected behavior was to show the hitboxes of invisible entities. However, due to changes made by Mojang, the code was actually rendering the entire entity model, since the entity was no longer considered invisible. This issue is resolved by using this new class and method :)



> > The internal code has changed and now entity models are shown instead of just rendering their hitboxes. Can you take a look at `EntityHitboxDebugRenderer#emitGizmos`?
> 
> can I reach you outside of git? something like discord would be amazing, I'm a mod in a discord server where we discuss [BBE](https://modrinth.com/mod/better-block-entities) and you're welcome to [join us](https://discord.gg/NdX9BYpTtz) :). I'm currently helping the dev since it's a huge mod, and talking and trying to figure stuff out here is kinda hard lol. feel free to add me: my dc id 268108477958848532. I will commit the changes you requested but I literally have no idea if that is what you wanted me to do since the end result seems to be the exact same, so please if you can reach me through discord 🙏 that would be a lot better and faster lol. it is totally fine if you don't want to though, no problem with that 👍

Yeah don't worry, this is exactly what you were supposed to do! I actually need your Discord username instead of the ID - you can add me @ItsJustMiaouss.

**Review by ItsJustMiaouss — APPROVED** [review]
Really good! Thanks again :)
